### ISSUE TITLE
Have the ability to edit issues you've created

### ISSUE THREAD

**Issue by seanauriti** [Bugheist/website#12]

**Comment by coderbounty-cowboy** [comment]
![Coderbounty](http://www.coderbounty.com/get_bounty_image/74/) http://coderbounty.com/issue/74

**Comment by rafen** [comment]
I created a pull request to complete this task: https://github.com/Bugheist/website/pull/98

**Comment by seanauriti** [comment]
Great work, bounty has been paid.  Thank you.
