### ISSUE TITLE
Have the ability to invite people and get a point

### ISSUE THREAD

**Issue by seanauriti** [Bugheist/website#13]
Add to the bottom of the page. 
Invite two friends and get 1 point.
Email says username invites you to www.bugheist.com
Hold the 2 emails in a table and show the status on the iser profile page.

When the emails both return delivered then issue the point and delete them from the table.

**Comment by coderbounty-cowboy** [comment]
![Coderbounty](http://www.coderbounty.com/get_bounty_image/76/) http://coderbounty.com/issue/76
