### ISSUE TITLE
I can search for domain without entering anything in the domain field and get +1 point, and that will show 500 error for a while.

### ISSUE THREAD

**Issue by RamiSaleem** [Bugheist/website#47]
I can search for domain without entering anything in the domain field and get +1 point, and that will show 500 error for a while.

**Comment by seanauriti** [comment]
Thanks for finding this!

**Comment by RamiSaleem** [comment]
Hello Sean,

I have reported more issues and posted them on http://www.bugheist.com.

Can I get your email please?

Thanks,
Rami
