### ISSUE TITLE
I can add "Sponsored Bug Hunts" before purchase any plan.

### ISSUE THREAD

**Issue by RamiSaleem** [Bugheist/website#50]
I can add "Sponsored Bug Hunts" before purchase any plan.

Actually I see many issues along of this process, I am not sure even if I can add Sponsored Bug Hunts and removed the already exiting Sponsors. The steps below will describe some of those functional and UX issues.

1- Click on "Start Hunting".
2- You will be navigated to the start bug hunting page "http://www.bugheist.com/start/"
3- Nothing there says that you are adding new "Sponsors".
4- Add URL and Image (it says squared image 1:1 with it's not squared on the homepage actually).
5- Click on "Start" from the bottom of the page (the blue one), or on "start" from any of the mentioned plans.
6- You will be navigated to PayPal login page! nothing told the user that you will navigated to the PP or checkout page, that's really weird UX.
7- On PP login page, I see the name of the merchant "CoderBountry" I am not sure if that intended.
8- Now, if you back to the homepage, you will see your added URLs and logos dispalyed under the "Sponsored Bug Hunts" and the old ones have been removed, it seems it shows only 5 sponsors.
9- The user will be surprised, how those have been added!
10- We need to add more clear path, and more communication messages for this path.
11- Also, the user is able to add the same Sponsor more than one, and cannot edit the already existing ones.

**Comment by seanauriti** [comment]
Great find.  Thank you for the detailed report.
