### ISSUE TITLE
The bug will not be created after completing the logging in process

### ISSUE THREAD

**Issue by RamiSaleem** [Bugheist/website#54]
![Coderbounty](http://www.coderbounty.com/get_bounty_image/71/)

The bug will not be created after completing the logging in process, this happens when the user add the big details first, and then complete the logging in process.

STR:
1- Navigate to http://www.bugheist.com/ as anonymous (not logged in).
2- Enter the bug description, url and screenshot.
3- Click on "Enter Bug" button.
4- You will be prompted to login.
5- Enter your info and complete the logging in process.
6- Observe the results, you already completed the logging in process, but the bug didn't enter, you will need to back and click once again on "Enter Bug" button.

This is a wrong flow and UX actually, in the mentioned case the bug should be cretaed after completing the logging process with no need to click on enter bug button once again.

**Comment by rafen** [comment]
I sent a Pull Request with a solution to http://www.coderbounty.com/issue/71/

**Comment by seanauriti** [comment]
This is pretty much closed, except one small issue here https://github.com/Bugheist/website/issues/99
