### ISSUE TITLE
The description is not linkable/clickable.

### ISSUE THREAD

**Issue by RamiSaleem** [Bugheist/website#56]
Not the whole description areas / <div> is clickable, for example you will not be able to navigate to the issue by clicking on the area between the lines, or on any white empty area.

The attahced screenshots
![2016-11-14_22-16-40](https://cloud.githubusercontent.com/assets/6474285/20281216/48b1009c-aab8-11e6-8c9b-7580ceb11503.jpg)
 will give you better idea.

The Expected: We need to make the parent <div> is linkable, so the user can navigate the issue by clicking on any area inside the issue section.

![area](https://cloud.githubusercontent.com/assets/6474285/20281128/e57d1a6a-aab7-11e6-9e6d-a6f493007c65.jpg)

**Comment by seanauriti** [comment]
We'll address this with the new design coming up soon.
