### ISSUE TITLE
I cannot scroll up/down the page while using the extension.

### ISSUE THREAD

**Issue by RamiSaleem** [Bugheist/website#60]
I cannot scroll up/down the page while using the extension.

1- Click on the extension button.
2- While the overlay is dispalyed, try to scroll the page.
3- Observe the results.
<img width="820" alt="screen shot 2016-11-15 at 6 56 48 pm" src="https://cloud.githubusercontent.com/assets/6474285/20315198/b4d2ce88-ab65-11e6-95fc-b9ce43d7c938.png">

**Comment by seanauriti** [comment]
The extension needs to freeze the page when it takes the screenshot, that is why it is unable to scroll. I don't think this is an issue, if you can find a similar screenshot tool that can scroll please let me know and I will make it work.  Thank you.
