### ISSUE TITLE
Add ability for users to edit their avatar.

### ISSUE THREAD

**Issue by seanauriti** [Bugheist/website#67]
Can code from here https://github.com/CoderBounty/coderbounty/blob/master/website/models.py#L189

**Comment by coderbounty-cowboy** [comment]
![Coderbounty](http://www.coderbounty.com/get_bounty_image/75/) http://coderbounty.com/issue/75

**Comment by rkirmizi** [comment]
https://github.com/CoderBounty/coderbounty/pull/292

**Comment by seanauriti** [comment]
@rkirmizi the task is for for Bugheist, not Coderbounty.

**Comment by rkirmizi** [comment]
Oh i was a bit confused, sorry about that.

**Comment by seanauriti** [comment]
@ordersys the task is for for Bugheist, not Coderbounty. I was giving the link as an example. Sorry if it was unclear.
