### ISSUE TITLE
Youtube show error.

### ISSUE THREAD

**Issue by RamiSaleem** [Bugheist/website#79]
![0](https://bhfiles.storage.googleapis.com/screenshots/js.jpg) http://bugheist.com/issue/209

**Comment by seanauriti** [comment]
This is a bug with Youtube... Feel free to report it again with the Youtube domain - https://code.google.com/p/gdata-issues/issues/detail?can=2&start=0&num=100&q=&colspec=API%20ID%20Type%20Status%20Priority%20Stars%20Summary&groupby=&sort=&id=8668
