### ISSUE TITLE
The user should be able to add bug or Suggestions without attaching screenshot.Some of the new features and enhancements has not specific attachment to be added.

### ISSUE THREAD

**Issue by RamiSaleem** [Bugheist/website#81]
![0](https://bhfiles.storage.googleapis.com/screenshots/newattach.jpg) http://bugheist.com/issue/207

**Comment by seanauriti** [comment]
We used to have this feature however we want to collect images on all issues so that we can OCR them, so we have made this a requirement for that reason.
