### ISSUE TITLE
Username is not associated to issue when posting after logging in.

### ISSUE THREAD

**Issue by seanauriti** [Bugheist/website#99]
![0](https://bhfiles.storage.googleapis.com/screenshots/c34e6c385224e7eac6c2347637e605d4.png) http://bugheist.com/issue/269

**Comment by rafen** [comment]
@seanauriti I created Pull Request: https://github.com/Bugheist/website/pull/101 to fix this

**Comment by seanauriti** [comment]
Thank you.  The bug was created correctly and it's ok for anonymous reports to show up, however I was not associated with the bug as expected.

**Comment by rafen** [comment]
@seanauriti does this issue happens all the time? or there are specifics steps to reproduce it?
I tried on my local environment and I couldn't reproduce it. Can you please provide more instructions? thanks! 

Note: one thing to have in mind is that this solutions uses the browser session, that means if an anon user submit a bug, we will only be able to assign it his user to the bug after login, if he uses the same browser in a relative short time.

**Comment by seanauriti** [comment]
I tested and it worked this time.  May have been a glitch when I deployed.  It works.  Thank you.

**Comment by seanauriti** [comment]
It happened again.  I think it is when there is a new domain and the screenshot is taken, it takes a while for that to run, then the username is not associated.

**Comment by seanauriti** [comment]
we're no longer taking a web screenshot on new domains so I don't think this is happening anymore.
